baseurl = "https://explorozcos.com"
canonifyURLs = false
defaultContentLanguage = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
enableRobotsTXT = true
footnoteReturnLinkContents = "&#8617;"
languageCode = "en-us"
pluralizelisttitles = false
rssLimit = 100
summaryLength = 40
theme = "axiom"
title = "ExplOrozcos"
[languages.en-us]
languageName = "US English"
weight = 1
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.parser]
attribute = false
autoHeadingID = false
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = false
noClasses = false
tabWidth = 2
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]
[[menu.foot]]
name = "About"
url = "/about/"
weight = 2
[[menu.foot]]
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.mobile]]
name = "Posts"
url = "/post/"
weight = 1
[[menu.mobile]]
name = "About"
url = "/about/"
weight = 2
[outputFormats.ATOM]
baseName = "feed"
mediaType = "application/atom+xml"
name = "ATOM"
[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]
[params]
copyrightYear = 2000
mainSections = ["post"]
[params.brand]
domain = "example.com"
email = "info@example.com"
[params.cdn]
provider = "local"
type = "image"
[params.cloudinary]
host = "https://res.cloudinary.com/deo07tbou/"
image = "image/upload/"
raw = "raw/upload/"
version = ""
video = "video/upload/"
[params.cloudinary.presets]
base = "f_auto,q_auto/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
[params.font]
files = []
path = ""
type = ""
[params.image]
default = "image/page-default.webp"
faviconAlt = "image/brand/favicon.png"
faviconIco = "favicon.ico"
height = "1024"
icon1To1 = "image/brand/icon-1-1.png"
icon2To1 = "image/brand/icon-2-1.png"
logo = "svginline"
width = "2048"
[params.services]
adsenseAdSlotId = "ID-DEV"
adsenseId = "CA-PUB-DEV"
adsenseLazy = false
adwordsConversionId = "ID-DEV"
adwordsConversionValue = 0
adwordsId = "AW-DEV"
analyticsId = "UA-DEV"
disqusUser = "na"
facebookApp = "FB-DEV"
facebookPixel = "FB-DEV"
[params.social]
[permalinks]
post = "/:filename"
