name: Push to GitHub Pages on push to master

on: push

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.0.0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.60.1'

      - name: Checkout submodules
        run: |
          git submodule sync && git submodule update --init

      - name: Build
        run: |
          hugo --theme=novela
          echo explorozcos.com > ./public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          emptyCommits: false
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
