name: Push to GitHub Pages on push to master

on: push

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.0.0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.1
        with:
          hugo-version: '0.60.1'

      - name: Checkout submodules
        run: |
          git submodule sync && git submodule update --init

      # - name: Deploy the site
      #   uses: benmatselby/hugo-deploy-gh-pages@master
      #   env:
      #     HUGO_VERSION: 0.60.1
      #     TARGET_REPO: EndGameStudio/www-explorozcos-com
      #     HUGO_ARGS: '--theme=novela'
      #     TOKEN: ${{ secrets.DEPLOYIT }}
      #     CNAME: www-explorozcos-com.github.io

      - name: Build
        run: hugo --theme=novela

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        # with:
        #   emptyCommits: false
        env:
          PERSONAL_TOKEN: ${{ secrets.DEPLOYIT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
