name: Push to GitHub Pages on push to master

on: push

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.0.0

      - name: Checkout submodules
        run: |
          git submodule sync && git submodule update --init

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.60.1
          TARGET_REPO: EndGameStudio/www-explorozcos-com.github.io
          HUGO_ARGS: "-v -t novela"
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: www-explorozcos-com.github.io
